Repository TimAtoyo/wonderGuard, pull requests merged in 2024-01, with the labels that each got.

#54 Adding images to image folder
  assets/images/currency-image.png
Labels: enhancement

#60 readme features updated
  README.md
Labels: documentation

#70 Updating the readme
  README.md
Labels: documentation, enhancement

#72 Documentation/finalreadme
  README.md
  assets/images/Webpage-demo
  assets/images/contact-us-modal.jpg
  assets/images/currency-convert-sect.jpg
  assets/images/front-page-1.jpg
  assets/images/front-page-2.jpg
  assets/images/mobile-view.jpg
  assets/images/search-hist-buttons.jpg
  assets/images/tablet-view.jpg
  assets/images/travel-advisory-section.jpg
  assets/images/webpage-responsive-demo
Labels: documentation

#73 Documentation/codecomments
  assets/css/style.css
  index.html
Labels: documentation, enhancement
